### ISSUE TITLE
Add model comparisons for pruning to the supplemental materials

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#11]
This means that model comparisons throughout the pruning process should be presented, too (e.g., in supplemental), especially because the pruning method used here differed from the one in the registered report.

**Comment by kristabh** [comment]
@angelinetsui plans to tackle this

**Comment by angelinetsui** [comment]
@kristabh, I re-ran the model and have listed how I pruned the model sequentially in 05.confirmatory_analysis.Rmd. Do you think that we need to put it in supplemental materials, or simply refer readers to the Rmd in text?

**Comment by kristabh** [comment]
Great! I think it would be okay to just leave in the RmD. I have added some wording to the manuscript and the response letter.  You can close this issue if you think we're good.

**Comment by kristabh** [comment]
The response now says "We have now included all of the pruning comparisons in the analysis code, and refer readers to this on p. XX."  I don't think you've pushed the change yet- is this an accurate description?

**Comment by angelinetsui** [comment]
Yes, I will check with this and push my changes later. I just want to double check everything before pushing.

@kristabh , I believe that I should push the changes to MB1B public repo, not the private one, right?

**Comment by kristabh** [comment]
Yes, public repo

**Comment by angelinetsui** [comment]
I will close this issue now, as I have pushed the changes to the OSF file in the public repo
