### ISSUE TITLE
Add Levene's Test

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#2]
p. 36: "We pre-registered a Levene’s test to examine whether monolinguals and bilinguals showed different amounts of variance in their IDS preference. However, we ultimately omitted this test because the null results of our within-group variability meta-analysis did not support  a difference between monolingual and bilingual infants in the variance of their IDS preference." -> Any harm in computing it as planned anyway and then noting that it’s likely not relevant? It seems better to stick to the plan as specified when possible. If it's not possible, that's different. But, if it's just not going to lead to a meaningful result, I'd still go ahead with what you said you'd do and then state why it's not meaningful.

**Comment by angelinetsui** [comment]
@kristabh , Should we just do Levene's test for matched dataset for LMM model 1 or both model 1 and 3? Note that I didn't include model 2 because model 2 only examined bilingual infants

**Comment by kristabh** [comment]
The question is whether bilinguals show higher variance in their preference than monolinguals.  So we should just use Levene's test to compare the variance of the bilinguals to the matched monolingual sample, as well as to the full monolingual sample.

**Comment by angelinetsui** [comment]
Currently, I am doing the Levene's test using the model residual with bilingualism. Does it make sense? https://stats.stackexchange.com/questions/255546/test-homogeneity-in-lmer-models

**Comment by kristabh** [comment]
Refer back to the pre-registered analysis plan and make sure to do exactly what we pre-registered.

**Comment by angelinetsui** [comment]
This is what copied from the MB1B analysis plan RR:

"Homogeneity of variance . As a preliminary but theoretically interesting analysis, we
planned to use Levene’s test to examine whether monolinguals and bilinguals show different
amounts of variance in their IDS preference. We note that Levene’s test is highly sensitive to
even small deviations from homogeneity of variance. If we find a statistically significant
result, we will follow-up by **examining residuals computed from the mixed-model
framework**."

I think that I am using the correct approach when doing a Levene's test using model residual with bilingualism? @kristabh

**Comment by angelinetsui** [comment]
I worked on all the Levene's tests. VERY surprisingly, one of the model's residual (i.e., LMM IDS full model dataset) indicates a significant difference in variability between monolinguals and bilinguals. This result was not significant for matched dataset. I wonder if:

1) in the full dataset, we have way more monolinguals than bilinguals. One possibility is that the variability is much more precise in the monolingual group but not bilinguals (i.e., bilinguals have larger variability just because of smaller samples); 
2) will change some of the interpretation of our general discussion; 
3) what needs to be done to deal with the violation of homogeneity of variance in LMM model (need time to investigate this matter further)

Please share your thoughts. @kristabh , @mcfrank  (sorry Mike, I know that you are very busy, but this is a surprising result and I want to hear what you think. I vaguely remember that LMM model is robust to homogeneity of variance if we have a large sample. Have you heard of this?)

**Comment by kristabh** [comment]
What is the magnitude of the effect, and is it in the predicted direction (bilinguals more variable)?  Since you are finding significance only with the larger dataset, it could be that we are overpowered (I think this is in line with your first point).

**Comment by angelinetsui** [comment]
@kristabh , may I ask what effect size are you referring to? The effect size of the mixed effect model is the corresponding beta coefficient. But the DV is log-transformed looking time, so are you referring to the effect size of "bilingualism" or the effect size of "bilingualism * IDS" ? I found the formula that calculates the effect size of the mixed level analysis. However, either effect size does not seem to measure the variability of each language group only. Instead, the effect size takes into account of the beta-coefficient, variance of the beta-coefficient and the residual variance. 

I also took a look of the sample sizes of the monolinguals and bilinguals in the matched and full dataset. I think that the monolinguals and bilinguals are much similar in the matched dataset: monolinguals_6-9_month: 181; bilinguals_6-9_month: 148; monolinguals_12-15_month: 203; bilinguals_12-15_month: 185. But for the full dataset, monolinguals' sample is much larger. Monolinguals_6-9_month: 755, monolinguals_12-15_month: 666 (numbers of children in bilingual group do not change). Based on the sample size, I wonder if it makes sense for running levees test for the matched dataset only?

**Comment by kristabh** [comment]
Perhaps effect size is the wrong word.  In the simple case, we could just calculate the variance for the bilingual group and the variance for the monolingual group, and compare them.  This "variance" (actually the difference in variance between the two groups) is what I was referring to the effect size.  If I understand correctly, running the Levene's on the residuals partitions out nuisance sources of variance like method, IDS exposure, etc., so we can look at the "pure" variance that is related to the bilingualism factor. These residuals may be statistically significantly different, but I am thinking about the degree to which they are meaningfully different. I have not done this type of analysis before, so apologies if I am misunderstanding.

**Comment by angelinetsui** [comment]
@kristabh , not a problem at all, thank you very much for clarification. I have been searching for solutions of dealing with the heterogeneity of variance and I still can't find a way to run a weighted variance mixed-level regression in lme4 package. Instead, it looks like that we may need to use nlme to do the correction, but then it means that we need to shift from lmer to nlme just for this model.......I am not totally sure this is what we need to do. Any thoughts?

Regarding your question about variability: it is very surprising. From my understanding, like what you said, a significant Levene test means that we have different residual variance between monolinguals and bilinguals in the model. However, when I calculated the residual variance for each language group in the full dataset model, I don't really think that they are really different: Monolinguals' variance = 0.2438553 and Bilinguals' variance = 0.2524367.....this is weird

**Comment by kristabh** [comment]
I would say for now, let's focus on the Levene's test and interpreting it.  If there is a variance difference, it's small and I suspect our analysis is robust enough to it.  I would not be in favour of changing the mixed models at this point.

**Comment by angelinetsui** [comment]
Yes, this is really weird, I tried to spend quite a bit of time yesterday to search for articles about "what to do if we violate homogeneity of variance" but didn't find much info....I will see if I can find some studies that support that with a large sample, our mixed effect model will be robust to heterogeneity of variance

**Comment by kristabh** [comment]
Again, I would suggest we focus on the Levene's test itself, and its interpretation. Given that only one of the two tests is even significant, and we don't have evidence of variance differences from our meta-analysis, it seems premature to change all the mixed models.

**Comment by angelinetsui** [comment]
yes, sorry for still not being able to find sufficient support in the literature about the robustness of the model that violates Levene's test. But I am wondering if I can seek some statisticians' advice will be good. I will keep you updated about the statisticians comment?

**Comment by angelinetsui** [comment]
Just got a reply from a statistician. Essentially, when there is a large sample (big N) and big differences in sample sizes between groups, levene's test will always be significant.......so we need to look into the residual variance difference (which we did) and if there is such a small difference, we do not need to worry at all. I think that we can very well justify this point in the paper

**Comment by kristabh** [comment]
Okay, this is what I thought. Please go ahead and add the statistics and the justification to the paper.  Let's work in the Google Doc for transparency (using placeholders for the actual numbers if necessary), and then we can add to the RmD.

**Comment by angelinetsui** [comment]
will do.
