### ISSUE TITLE
Coefficients not printing properly from lines 1090, 1342

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#33]
None of these values is printing properly:

Line 1090: The main effect of infants' exposure to NAE (exp_nae) was not significant ($\beta$ = `r signif(nae_exp_coef["EXP_NAE", "Estimate"], 2)`, $SE = `r signif(nae_exp_coef["EXP_NAE", "SE"], 2)`$, $p = `r signif(nae_exp_coef["EXP_NAE","p"], 2)`)$.

Line 1090: However, the interaction between trial type and exp_nae was significant ($\beta$ = `r signif(nae_exp_coef["IDS * EXP_NAE","Estimate"], 3)`, $SE = `r signif(nae_exp_coef["IDS * EXP_NAE","SE"], 2)`$, $p = `r signif(nae_exp_coef["IDS * EXP_NAE", "p"], 2)`)$.

Line 1342: the interaction between Trial Type and NAE exposure was still statistically significant ($\beta$ = `r signif(nae_only_coef["IDS * EXP_NAE","Estimate"], 3)`, $SE = `r signif(nae_only_coef["IDS * EXP_NAE","SE"], 2)`$, $p = `r signif(nae_only_coef["IDS * EXP_NAE", "p"], 2)`)$.

**Comment by jkosie** [comment]
I'll try to fix it. I think when I add the blank spaces to the bottom of the table (to center the r2 measures), it turns the columns into characters rather than numbers and then things get messed up.

**Comment by jkosie** [comment]
I have to stop for today, but I've fixed part of it and submitted a pull request. They are now actual values and not NAs. However, the values are automatically rounded to 2 decimal places no matter what I tell it to round to (I think because of the stats annotation...with the $s). So, some of the values are reported as 0. I can take another look tomorrow unless someone else knows how to quickly fix that!

**Comment by kristabh** [comment]
It would be great if you can take another look today... thx!

**Comment by jkosie** [comment]
I just spent quite a bit of time on it, but I still can't get the numbers to round correctly when values are small. Even when I ask it to round a number to 3 decimal places (using either `round` or `signif`), I'm still getting just 0.00. For example, 0.001128 keeps being reported as 0.00 even if I specify 3 decimal places (with the intention of rounding to 0.001). 

I haven't been able to find anything on google, and it looks like we didn't have numbers this small in mb1, so it wasn't an issue.

@christinabergmann - have you encountered this before?

**Comment by kristabh** [comment]
I tried with format() including the digits argument, and that seems to work.  Clue from this post https://stackoverflow.com/questions/3245862/format-numbers-to-significant-figures-nicely-in-r

**Comment by jkosie** [comment]
Weird - I tried format at one point too. At least it works now! :)

**Comment by kristabh** [comment]
Yeah, I have no idea why signif was not working...  It worked in the console, but not when knitted.  Agreed, at least the problem is solved :-)
