### ISSUE TITLE
Replace labids in Table 1 and Figure 1

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#37]
From the editor: "For Table 1 and Figure 1, please replace the lab nicknames either with the university/ institution name or with the PI name (I' prefer institution). Readers won't know what "babylabbrookes" means, for example. Using institution names will make it easier for readers to associate authors with the data they contributed (more transparent and easier to parse). "

Let's go with the institution names.  We can create a lookup .csv file in the metadata folder, and then implement this in the code when creating the Table and Figure.

**Comment by jkosie** [comment]
I can do this quickly today.

**Comment by jkosie** [comment]
One issue I just came across. There are two labs from UBC - how should I handle this?

**Comment by kristabh** [comment]
I'd suggest University of British Columbia (Werker) & University of British Columbia (Hamlin) to denote the PIs.

**Comment by christinabergmann** [comment]
This seems fine now?
