### ISSUE TITLE
Improve order of labs in Table 1

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#4]
p. 23, Table 1. Please list the labs in a more informative order, e.g., group by method? Better yet, whether they have significant NAE exposure, since that is the variable of interest. In any case, alphabetical by some random lab name is not informative.

**Comment by kristabh** [comment]
Ideally, group by NAE exposure.

**Comment by kristabh** [comment]
See also comment, asking for same info "Figure 2. I was surprised by how many data points had 0% NAE exposure.  Perhaps setting this up earlier, e.g., in Table 1 and with an additional descriptive table, would help the reader. There’s a lot to keep track of and a lot of detail, so any way that you can organize things to help the reader would be helpful."

**Comment by jkosie** [comment]
Table 1 is now grouped by NAE exposure.
