### ISSUE TITLE
Reference list appears twice

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#43]
For some reason, the entire reference list repeats when the paper is knit.  Any idea how to fix this @angelinetsui @christinabergmann @jkosie ?  I'm stumped.

**Comment by jkosie** [comment]
Have you tried updating rmarkdown? I just knit it on my end and it didn't duplicate the references. I did have this problem before, though, and I think updating rmarkdown fixed it.

**Comment by kristabh** [comment]
Great suggestion!  I updated tinytex and papaja and that did it!  Thanks!
