### ISSUE TITLE
Problem with Exclusions.RmD

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#45]
In checking the .doc against the .pdf versions, @hilary-rose noticed that knitting in these two ways gives different numbers of infants excluded for each reason.  I suspect that this somehow has something to do with the order in which the code is executed when knitting to the different formats, which gives some differences because some infants have multiple reasons for being excluded. I'm okay with going as the .pdf as the authoritative order.

Somewhat more concerningly, though, the total excluded infants do not add up to each other, or to the total excluded infants that we report.  Maybe something to do with some bilinguals being in the monolingual dataset?  One hypothesis.  Can anybody look into this? @jkosie @angelinetsui @christinabergmann

**Comment by christinabergmann** [comment]
Urgh, that sounds annoying and I can't think of an obvious reason this is happening. I can't dedicate time to proper digging through everything before the 15th, so if someone else has a moment earlier, that'd be great. Otherwise just ping me again.

**Comment by kristabh** [comment]
Thanks for your responses - it is a busy time for us all.  @hilary-rose is working on it right now, and seems to be making some progress!

**Comment by jkosie** [comment]
I think I can take some time later in the week if it hasn't been figured out by then!

**Comment by kristabh** [comment]
Seems there was an issue with the text not reporting all of the exclusions the code was implementing, as well as an issue where NAs that should have been recoded as "FALSE" were not, and so that was not being counted. Thanks to @hilary-rose for figuring things out!  I have now fixed the issues and pushed the updated code, so I'll close this issue.
