### ISSUE TITLE
Confirm number of lab-matched monolinguals

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#48]
There are inconsistencies in the manuscript:
Abstract says 385 (but that's hard coded)
Text says 384
Table A1 totals to 383

**Comment by angelinetsui** [comment]
I checked the codes in paper.Rmd. I think it should be 384, and now I also checked the codes in Appendix A1, and I think Jessica and I called the exact same files and I can't figure out why there is one number missing in A1. I need help

**Comment by kristabh** [comment]
Yes, it would be good to find out what happened to that baby so we can be sure that the number is 384.  Tagging @jkosie

**Comment by jkosie** [comment]
I'm working on this now. I can see that the numbers in table A1 total to 383. However, I only see 385 in the abstract and text. I don't see anywhere that it says 384. Could you point me to the place you see that number?

**Comment by jkosie** [comment]
Strange...I just figured out that when I knit the document it says 385, but when I look at the code in the mb1b-paper.Rmd file it says 384.

I think I did figure out the issue from table A1, though (if 384 is the correct number of lab-matched monolinguals). There is one infant who has NA for their gender, so they're getting dropped out of the table.

**Comment by angelinetsui** [comment]
I have the same issues. When I knitted the file, it changed to 384 even the code generated 384......and yes, for the table A1, I think the missing infant is due to "0"/NA gender

**Comment by jkosie** [comment]
I think this might be similar to issue #45 

When I knit to a docx file, the number is 384. So, I think it might be something about when exclusions are running. I'll keep trying to figure it out.

**Comment by kristabh** [comment]
Okay, confirm that 384 is the correct number of lab-matched monolinguals. In the manuscript I've added a note to the appendix Table A1 "Data on gender was missing for one additional infant from babylabbrookes"
