### ISSUE TITLE
Add N's and degrees of freedom to each results table

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#7]
"Related to the final number of participants, I had trouble tracking whether all the exclusion criteria used in the final paper were mentioned in the registered report. Regardless, reducing a sample of 501 to 333 is concerning. It is also very difficult to know the final sample sizes that went into all analyses. N’s and/or degrees of freedom should be presented with results (e.g., as table notes). "

**Comment by christinabergmann** [comment]
I can try to work on this next week - if anyone ants to tackle it earlier or there's a deadline, just let me know.

**Comment by kristabh** [comment]
That would be perfect if you can work on this next week- thanks!!

**Comment by christinabergmann** [comment]
Sorry for the delay. This comment has two parts. First, the reviewer is wondering whether all exclusion criteria were listed in the Stage 1 manuscript, if I understand correctly. 
Looking back at the Stage 1 Manuscript, we listed the following criteria, where I am inserting numbers for clarity.

> 
Data from participants who 
1. were not full term (less than 37 weeks gestation: N = XX), 
2. had a reported developmental disorder according to parental report (N = XX), 
3. were outside the target age groups (N= XX), 
4. did not meet language inclusion criteria (e.g., did not meet our criteria for being either monolingual or bilingual; N = XX), or 
5. had a session-level testing error (e.g., parent talking during study, technical problems; N = XX) were excluded from the confirmatory analyses. 
6. We also excluded any infant who did not have at least one IDS-ADS trial pair available for analysis (N = XX). 
7. For infants with at least one good trial pair, we additionally excluded any trial with less than 2 s of looking (N = XX trials)
> 

Now we exclude, in that order: 

- 59 for age 
- 74 who don't meet the bilingualism criteria defined earlier in the paper
- 4 preterm
- 2 for diagnosed developmental disorder
- 6 for session-level errors (equipment, experimenter, outside interference)
- 5 for not enough trials for analysis

That matches pretty well, but the order is a bit mixed up, so I propose to move term and developmental delay up in the hierarchy or argue that age excludes more and thus is a better check and more efficient. 

I also don't think this exclusion rate is concerning. Does anyone have exclusion rates from comparable studies with bilinguals? Might be nice to add to the response. 

Regarding the second part, should N be in the table caption or in the running text? I'll try how the latter looks (once I got papaja reinstalled, ha, new R version).

**Comment by kristabh** [comment]
Hi, thanks for looking into this.  I think it's probably easier just to exclude in the order that we had in the manuscript.  I agree that this isn't really an unusual exclusion rate for baby studies, but I get the sense that that reviewers are more experts on registered reports than infants, because this is what most questions were about (I could be wrong- they could be experts in both).  So perhaps that reviewer doesn't have perspective.

Here's a recent study from my lab with bilingual infants, and a similar HPP paradigm - exclusions seem similar, although there's no age exclusions:

https://psyarxiv.com/xkc9b/

The final sample was 21 bilingual and 20 monolinguals. "To achieve the final sample, 68 infants and their families participated in the study. Two participants were tested during a pilot phase to verify that the study procedure was feasible, and were not included in data analysis. Of the remaining infants, one was born prematurely (< 37 weeks) and thus did not meet our health criteria, and 16 did not meet the pre-specified language criteria. Four infants were excluded for technical difficulties or experimenter error. Additionally, four were excluded for contributing fewer than eight trials with at least 2.5 s of looking time."

**Comment by kristabh** [comment]
For the Ns, sounds perfect if you just see how it looks- I might prefer in Table if possible.

**Comment by christinabergmann** [comment]
OK, I've done the first part but since papaja still doesn't work, @angelinetsui - feel free to check. I can't test how Ns in tables look like, but I can still edit them into the captions, if you'd like.

**Comment by angelinetsui** [comment]
@christinabergmann , thanks Christina. May I ask if you have pushed?

**Comment by christinabergmann** [comment]
Check exclusions.Rmd and the mention in this issue

angelinetsui <notifications@github.com> schrieb am Do., 2. Juli 2020, 16:52:

**Comment by angelinetsui** [comment]
checked, it knitted well on my side.

**Comment by jkosie** [comment]
I mentioned this in another issue, but wanted to update that I've added Ns to tables 2 through 7 (in a separate row at the bottom). See below for an example of what it looks like. 

![Screen Shot 2020-07-08 at 10 40 42 AM](https://user-images.githubusercontent.com/7671648/86933179-446b4000-c108-11ea-9c5a-76a03cf16600.png)

**Comment by kristabh** [comment]
Great, looks like this issue can be closed?

**Comment by jkosie** [comment]
I think so. I'll go ahead and close it.

Let me know if you'd like me to edit the table format at all.
