### ISSUE TITLE
Add estimated R-squared to models

### ISSUE THREAD

**Issue by kristabh** [manybabies/mb1b-analysis-public#9]
"Also, all models should have some overall model fit indices presented (e.g., comparison of AICs or estimated R-squared) instead of just the coefficients of the final models."

**Comment by angelinetsui** [comment]
Checked. I can calculate model fit indices via the package "performance". Here is my suggestion, report both conditional and marginal R-squared, but not AIC. Conditional R-squared takes both fixed and random effects into consideration, but marginal R-squared only takes into account of fixed. So reporting both will be nice.
For AIC, I don't think that it is very useful as we don't compare models here?

**Comment by kristabh** [comment]
Yes, I agree about reporting the conditional and marginal R-squared, and not AIC.

**Comment by angelinetsui** [comment]
Tagging @jkosie here as Jessica kindly offers helping me to include model fit index in the mixed-effect models. Thanks again, Jessica

**Comment by jkosie** [comment]
done!

The way I did it is a little hacky, but I think it looks okay. I've attached a screen shot, but please let me know if you'd like me to change anything.

![Screen Shot 2020-07-07 at 10 23 28 AM](https://user-images.githubusercontent.com/7671648/86796266-69927c80-c03c-11ea-89b6-8f485533ad67.png)

**Comment by kristabh** [comment]
Yeah, this looks okay.  Can you include n in the table as well?  Or did we end up putting that elsewhere...?

**Comment by jkosie** [comment]
To get the ns, I looked at the number of unique subids in the 'd_lmer_matched' and 'd_lmer_unmatched' data files (that are used to calculate the LMMs). I used this code: `length(unique(d_lmer_matched$subid)` 

I came up with 717 unique 'matched' subids and 1754 unique 'unmatched' subids that are contributing to the model. These numbers seem too large to me. Before I look into it further or add them to the table, could I be missing something obvious? (tagging @angelinetsui  too)

Thanks!

**Comment by angelinetsui** [comment]
@jkosie , thanks so much, Jessica. 

For the number of samples, it looks correct as we are using all data in mixed models.

For the table, will it be possible to change R2_square to R(2) where 2 is a superscript. Also, will it be possible to center the number of the R2_square?

Thanks again!

**Comment by jkosie** [comment]
Thanks, @angelinetsui 

I'll try those edits. 

Just to quickly double check about the number of participants. The "final sample" section of the manuscript says:

For the "matched" sample, there were 333 infants from the bilingual sample who met exclusion criteria, and 385 monolingual infants from the same labs who met inclusion criteria. This would be 718 infants, so I think we might be losing one somewhere. 

For the "unmatched" sample there were an additional 583 6-9 month olds and 468 12-15 month olds. If we add this to the 718 "matched" infants, it should be 1769. So again, we are losing 15 infants somewhere.

**Comment by angelinetsui** [comment]
Hi Jessica, this is interesting, I wonder if it is because we log-transform the looking time, we may lose additional data. For example, we did filter(!is.na(log_lt), !is.infinite(log_lt)) before running any analyses

**Comment by jkosie** [comment]
That's a good suggestion. I'll check and see if we're losing babies there.

**Comment by angelinetsui** [comment]
Yes, I think so, I double checked. For example, d_lmer_matched and we lost one infant right after we execute filter(!is.na(log_lt), !is.infinite(log_lt)). The same happens for d_lmer_unmatched.

Good catch, Jessica. We need to clarify this point in the manuscript!! :-)

**Comment by jkosie** [comment]
Okay, I centered the numbers and added the Ns to the tables (as well as tables 4, 5, 6, and 7).

I've tried a number of things to get superscripts in the row names, but I haven't had success. Does anyone else know how to do this?

**Comment by kristabh** [comment]
We'll just have to fix this at the stage of proofs I think... not sure how to get the superscripts we want here.

**Comment by jkosie** [comment]
Sounds good. I think this can be closed, too, but maybe we want to make another issue about the fact that a number of infants are getting removed when the data are log transformed?

**Comment by angelinetsui** [comment]
Hello Jessica, thanks for your work. I don't know how to fix the superscript too....may be we can write out "R square" instead, any thoughts @kristabh ?

Btw, Jessica, may I ask why we need to open another issue for the number of infants getting removed from the analyses when LT is log-transformed? We can clarify it in the manuscript and we found the reason why they are removed

**Comment by jkosie** [comment]
I was just thinking to track the issue and make sure it gets clarified in the manuscript (i.e., we can close it once it's finished). Probably fine not to start an issue, though, and just change it in the manuscript.

**Comment by angelinetsui** [comment]
Thanks for sharing your thoughts, Jessica. Let us leave this issue open until we clarified this point in the manuscript, shall we?

To all, sorry for the slow response to the manuscript, have been attending vICIS this week...can't really work much

**Comment by angelinetsui** [comment]
@jkosie , we solved the problem for NA looking time for the monolinguals, so are we good now, can we close this issue? I want to confirm with you all before I edit the Paper.Rmd

**Comment by jkosie** [comment]
Seems good to me! I'll close :)

**Comment by kristabh** [comment]
@jkosie would you be able to open the R-squared to the models for SES and NAE, as you did for the main models?  The timeline is tight, as we're trying to finalize the manuscript this week.

**Comment by jkosie** [comment]
Done! 

I just submit a pull request. The only problem that came up was that the tables became too large to fit on the page (and were cut off at the bottom). I fixed this by changing the spacing of the tables (added code to the YAML at the top). The tables are more tightly spaced now, but they fit on the page. 

Here's the code I added at the top of the Rmd file.  I think the values I chose work, but you can play around with the stretch and size parameters if you want to change things around.

header-includes:
   - \usepackage{amsmath}
   - \usepackage{setspace}
   - \captionsetup[figure]{font={stretch=3,normalsize}}

Also, I think the first time you knit using this new code, the setspace package will install, so it takes longer to knit (but only the first time...after that the package is installed).
